import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import Footer from '@/components/Footer';
import './globals.css';
import CartProvider from '@/context/CartProvider';
import ToastProvider from '@/context/ToastProvider';
import ToastShelf from '@/components/ToastShelf';
import FocusOnHeading from '@/components/FocusOnHeading';
import Button from '@/components/Button';
import Link from 'next/link';

const manrope = Manrope({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <a href="#main" id="skip-link">
          Skip to Main Content
        </a>
        <FocusOnHeading />
        <ToastProvider>
          <CartProvider>{children}</CartProvider>
          <ToastShelf />
        </ToastProvider>
        <Footer />
      </body>
    </html>
  );
}
